name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-boost
          mingw-w64-ucrt-x86_64-openvr
          zip

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Package
      run: |
        cd build
        cp ../openvr_battery_monitor.conf .
        for i in libgcc_s_seh-1.dll libwinpthread-1.dll libopenvr_api.dll libstdc++-6.dll; do cp /ucrt64/bin/$i .; done
        zip openvr_battery_monitor.zip *.dll openvr_battery_monitor.exe openvr_battery_monitor.conf

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: build/openvr_battery_monitor.zip
        draft: false
        prerelease: false
